version: '3.2'

services:
  db:
    image: postgres
    container_name: database-contatos
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contatos
    ports:
      - "5432:5432"